[2016-04-24 10:22:03] local.ERROR: exception 'ErrorException' with message 'Undefined index: supervisor' in E:\xampp\htdocs\connect\app\models\SkillsMapV7.php:550
Stack trace:
#0 E:\xampp\htdocs\connect\app\models\SkillsMapV7.php(550): Illuminate\Exception\Handler->handleError(8, 'Undefined index...', 'E:\\xampp\\htdocs...', 550, Array)
#1 E:\xampp\htdocs\connect\app\controllers\SkillsMapControllerV7.php(394): SkillsMapV7::getSkillProficiencyData('37', 'supervisor')
#2 [internal function]: SkillsMapControllerV7->getSkillData()
#3 E:\xampp\htdocs\connect\vendor\laravel\framework\src\Illuminate\Routing\Controller.php(231): call_user_func_array(Array, Array)
#4 E:\xampp\htdocs\connect\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(93): Illuminate\Routing\Controller->callAction('getSkillData', Array)
#5 E:\xampp\htdocs\connect\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(62): Illuminate\Routing\ControllerDispatcher->call(Object(SkillsMapControllerV7), Object(Illuminate\Routing\Route), 'getSkillData')
#6 E:\xampp\htdocs\connect\vendor\laravel\framework\src\Illuminate\Routing\Router.php(967): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'SkillsMapContro...', 'getSkillData')
#7 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#8 E:\xampp\htdocs\connect\vendor\laravel\framework\src\Illuminate\Routing\Route.php(109): call_user_func_array(Object(Closure), Array)
#9 E:\xampp\htdocs\connect\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1033): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#10 E:\xampp\htdocs\connect\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1001): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#11 E:\xampp\htdocs\connect\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(775): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#12 E:\xampp\htdocs\connect\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(745): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#13 E:\xampp\htdocs\connect\vendor\laravel\framework\src\Illuminate\Session\Middleware.php(72): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#14 E:\xampp\htdocs\connect\vendor\laravel\framework\src\Illuminate\Cookie\Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#15 E:\xampp\htdocs\connect\vendor\laravel\framework\src\Illuminate\Cookie\Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#16 E:\xampp\htdocs\connect\vendor\stack\builder\src\Stack\StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#17 E:\xampp\htdocs\connect\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(641): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#18 E:\xampp\htdocs\connect\index.php(49): Illuminate\Foundation\Application->run()
#19 {main} [] []
[2016-04-24 10:22:24] local.ERROR: exception 'ErrorException' with message 'Undefined index: supervisor' in E:\xampp\htdocs\connect\app\models\SkillsMapV7.php:550
Stack trace:
#0 E:\xampp\htdocs\connect\app\models\SkillsMapV7.php(550): Illuminate\Exception\Handler->handleError(8, 'Undefined index...', 'E:\\xampp\\htdocs...', 550, Array)
#1 E:\xampp\htdocs\connect\app\controllers\SkillsMapControllerV7.php(394): SkillsMapV7::getSkillProficiencyData('37', 'supervisor')
#2 [internal function]: SkillsMapControllerV7->getSkillData()
#3 E:\xampp\htdocs\connect\vendor\laravel\framework\src\Illuminate\Routing\Controller.php(231): call_user_func_array(Array, Array)
#4 E:\xampp\htdocs\connect\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(93): Illuminate\Routing\Controller->callAction('getSkillData', Array)
#5 E:\xampp\htdocs\connect\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(62): Illuminate\Routing\ControllerDispatcher->call(Object(SkillsMapControllerV7), Object(Illuminate\Routing\Route), 'getSkillData')
#6 E:\xampp\htdocs\connect\vendor\laravel\framework\src\Illuminate\Routing\Router.php(967): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'SkillsMapContro...', 'getSkillData')
#7 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#8 E:\xampp\htdocs\connect\vendor\laravel\framework\src\Illuminate\Routing\Route.php(109): call_user_func_array(Object(Closure), Array)
#9 E:\xampp\htdocs\connect\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1033): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#10 E:\xampp\htdocs\connect\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1001): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#11 E:\xampp\htdocs\connect\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(775): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#12 E:\xampp\htdocs\connect\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(745): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#13 E:\xampp\htdocs\connect\vendor\laravel\framework\src\Illuminate\Session\Middleware.php(72): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#14 E:\xampp\htdocs\connect\vendor\laravel\framework\src\Illuminate\Cookie\Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#15 E:\xampp\htdocs\connect\vendor\laravel\framework\src\Illuminate\Cookie\Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#16 E:\xampp\htdocs\connect\vendor\stack\builder\src\Stack\StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#17 E:\xampp\htdocs\connect\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(641): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#18 E:\xampp\htdocs\connect\index.php(49): Illuminate\Foundation\Application->run()
#19 {main} [] []
[2016-04-24 10:45:10] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected 'else' (T_ELSE)' in E:\xampp\htdocs\connect\app\storage\views\183ded31e0eb2a9ab9211dad27920acd:1874
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
